services:
  - type: web
    name: youtube-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: false
    disk:
      name: youtube-api-disk
      mountPath: /tmp
      sizeGB: 1